// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJWZcZxLLAE5G6-jVBNX4e_IIQGZKN9R0',
    appId: '1:1091776145292:web:c071e83372adec169718a9',
    messagingSenderId: '1091776145292',
    projectId: 'smart-farm-app-123',
    authDomain: 'smart-farm-app-123.firebaseapp.com',
    storageBucket: 'smart-farm-app-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc9IdLq3qZqpy61n_A_qB1yUvHobHInL8',
    appId: '1:1091776145292:android:0f5a3ef1535bcea49718a9',
    messagingSenderId: '1091776145292',
    projectId: 'smart-farm-app-123',
    storageBucket: 'smart-farm-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTgbali_yzSQ8vocuUB-PWxsM9H7xGFOs',
    appId: '1:1091776145292:ios:0ee10d8ee227313a9718a9',
    messagingSenderId: '1091776145292',
    projectId: 'smart-farm-app-123',
    storageBucket: 'smart-farm-app-123.firebasestorage.app',
    iosClientId: '1091776145292-4ufc5jqi7napfp8orli289jfi3mntmbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartfarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTgbali_yzSQ8vocuUB-PWxsM9H7xGFOs',
    appId: '1:1091776145292:ios:0ee10d8ee227313a9718a9',
    messagingSenderId: '1091776145292',
    projectId: 'smart-farm-app-123',
    storageBucket: 'smart-farm-app-123.firebasestorage.app',
    iosClientId: '1091776145292-4ufc5jqi7napfp8orli289jfi3mntmbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartfarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJWZcZxLLAE5G6-jVBNX4e_IIQGZKN9R0',
    appId: '1:1091776145292:web:2b05fc60cf8202a79718a9',
    messagingSenderId: '1091776145292',
    projectId: 'smart-farm-app-123',
    authDomain: 'smart-farm-app-123.firebaseapp.com',
    storageBucket: 'smart-farm-app-123.firebasestorage.app',
  );

}